# ChittyConnect Configuration for chittysync
service:
  name: chittysync
  display_name: Chittysync
  type: service
  tier: 3
  organization: CHITTYOS
  chitty_id: ${CHITTYSYNC_SERVICE_ID}
  domains:
    production: sync.chitty.cc

onboarding:
  endpoint: https://get.chitty.cc/api/onboard
  provisions: [chitty_id, service_token, certificate, trust_chain]

auth:
  provider: chittyauth
  endpoint: https://auth.chitty.cc
  service_token:
    source: chittyconnect
    key: CHITTYSYNC_SERVICE_TOKEN

secrets:
  provider: chittyconnect
  vault: 1password
  paths:
    production: op://ChittyOS/chittysync-prod

github:
  repository: CHITTYOS/chittysync

monitoring:
  health:
    endpoint: /health
    interval: 60s
